---
apiVersion: v1
kind: Secret
metadata:
  name: frontendas1-app-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/frontendas1-app-gitops
